---
extends: default

rules:
  line-length:
    max: 200
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: true
  comments:
    require-starting-space: true
    min-spaces-from-content: 1
  document-start:
    present: true
  indentation:
    spaces: 2
    indent-sequences: true
  empty-lines:
    max: 1
  trailing-spaces: enable
  key-duplicates: enable
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
