---
# Staging inventory — jol-deploy
all:
  children:
    web_servers:
      hosts:
        her-staging-lt01:
          ansible_host: 10.40.40.120
    ai_services:
      hosts: {}
    management:
      hosts: {}
  vars:
    ansible_user: jol-admin
    ansible_python_interpreter: /usr/bin/python3
    jol_environment: staging
